package com.example.datagov.modules.review.application;
import com.example.datagov.common.*;
import com.example.datagov.infrastructure.Db;
import com.example.datagov.infrastructure.idempotency.CommandExecutor;
import com.example.datagov.modules.workorder.application.WorkorderService;
import com.example.datagov.security.PrincipalContext;
import org.springframework.stereotype.Service;
import java.util.*;
import static com.example.datagov.common.Checks.*;
import static com.example.datagov.modules.workorder.domain.WorkOrderPolicy.*;
@Service public class ReviewService {
 private final Db db;private final WorkorderService orders;private final CommandExecutor commands;
 public ReviewService(Db db,WorkorderService orders,CommandExecutor commands) { this.db=db;this.orders=orders;this.commands=commands; }
 public Object task(String key,String orderId,int roundNo,long expected,String source,Object body) { return commands.execute("review:execute",key,body,()->{var w=orders.load(orderId,true);version(Db.num(w,"version"),expected);state(Db.str(w,"status"),"WAIT_REVIEW");round(Db.num(w,"current_round"),roundNo);require("MANUAL".equals(source),422,ErrorCode.INVALID_ASSOCIATION,"执行器复检尚未开启");require(w.get("valid_pass_id")==null,409,ErrorCode.STATE_CONFLICT,"当前轮次已有有效PASS，不能重复创建任务");var submission=db.one("SELECT * FROM remediation_round WHERE work_order_id=? AND round_no=?",orderId,roundNo);independent(PrincipalContext.current().id(),Db.str(submission,"submitted_by"));require(db.count("SELECT COUNT(*) FROM review_task WHERE active_round_id=?",Db.str(submission,"id"))==0,409,ErrorCode.STATE_CONFLICT,"当前轮次已有活动任务");int attempt=(int)db.count("SELECT COUNT(*) FROM review_task WHERE round_id=?",Db.str(submission,"id"))+1;String task=db.insert("INSERT INTO review_task(work_order_id,round_id,rule_version_id,bound_work_order_version,requested_by,source_type,status,attempt_no) VALUES(?,?,?,?,?,'MANUAL','PENDING',?)",orderId,Db.str(submission,"id"),Db.str(submission,"rule_version_id"),expected,PrincipalContext.current().id(),attempt);orders.event(w,"WAIT_REVIEW","REVIEW_TASK","创建独立复检任务",null,Map.of("taskId",task));var out=Db.dto(db.one("SELECT * FROM review_task WHERE id=?",task));out.remove("activeRoundId");out.put("taskId",task);out.put("boundVersion",expected);return out;}); }
 public Object result(String key,String orderId,String taskId,int roundNo,long expected,String result,String reason,String evidence,Object body) { return commands.execute("review:execute",key,body,()->{var w=orders.load(orderId,true);version(Db.num(w,"version"),expected);state(Db.str(w,"status"),"WAIT_REVIEW");round(Db.num(w,"current_round"),roundNo);var transition=review(result,roundNo);var t=db.one("SELECT t.*,s.round_no,s.submitted_by,s.rule_version_id AS submission_rule FROM review_task t JOIN remediation_round s ON s.id=t.round_id WHERE t.id=? FOR UPDATE",id(taskId));require(orderId.equals(Db.str(t,"work_order_id"))&&"MANUAL".equals(t.get("source_type"))&&"PENDING".equals(t.get("status"))&&Db.num(t,"round_no")==roundNo&&Db.num(t,"bound_work_order_version")==expected&&Db.str(t,"rule_version_id").equals(Db.str(t,"submission_rule")),409,ErrorCode.VERSION_CONFLICT,"任务已完成或绑定的轮次版本已失效");require(PrincipalContext.current().id().equals(Db.str(t,"requested_by")),403,ErrorCode.FORBIDDEN,"仅任务请求人可以提交手工复检");independent(PrincipalContext.current().id(),Db.str(t,"submitted_by"));text(reason,2000);if(!"ERROR".equals(result))orders.proof(evidence,orderId,PrincipalContext.current().id());String hash=sha256((taskId+"\n"+result+"\n"+reason+"\n"+evidence).getBytes(java.nio.charset.StandardCharsets.UTF_8));String reviewId=db.insert("INSERT INTO review_result(task_id,reviewer_id,result,reason,proof_evidence_id,trusted_source,result_hash,valid,completed_at) VALUES(?,?,?,?,?,'MANUAL',?,1,UTC_TIMESTAMP(3))",taskId,PrincipalContext.current().id(),result,reason,"ERROR".equals(result)?null:evidence,hash);db.update("UPDATE review_task SET status=?,version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=?","ERROR".equals(result)?"ERROR":"DONE",taskId);db.update("UPDATE governance_work_order SET status=?,current_round=?,valid_pass_id=?,version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=?",transition.state(),transition.round(),transition.validPass()?reviewId:null,orderId);orders.event(w,transition.state(),"REVIEW_"+result,reason,reviewId,Map.of("reviewResultId",reviewId,"taskId",taskId,"roundNo",roundNo,"reviewerId",PrincipalContext.current().id(),"ruleVersionId",Db.str(t,"rule_version_id")));var out=new LinkedHashMap<String,Object>();out.put("reviewResultId",reviewId);out.put("valid",true);out.put("status",transition.state());out.put("currentRound",transition.round());out.put("version",expected+1);out.put("canClose",transition.validPass()&&PrincipalContext.current().permissions().contains("workorder:close"));return out;}); }
 public Object pending(String id) { throw new BusinessException(ErrorCode.FORBIDDEN,403,"执行器接口未开启且不接受普通用户身份"); }
}
