package com.example.datagov.common;
public enum ErrorCode { NOT_IMPLEMENTED, UNAUTHENTICATED, FORBIDDEN, INVALID_REQUEST, NOT_FOUND, INTERNAL_ERROR, VERSION_CONFLICT, STATE_CONFLICT, IDEMPOTENCY_CONFLICT, INVALID_PROOF, INVALID_ASSOCIATION, UNSUPPORTED_FILE }
