<script setup lang="ts">
// FR-RULE-001/002; D18-API-018/019/056..059; TC-RULE-001..003
import {ref,reactive,onMounted} from 'vue';import {useAuthStore} from '../../stores/auth';import {get,command,errorText,type Row,type Page} from '../../api/implemented';import {type Rule,type Standard,type Snapshot,ruleTypes,versionStates,constraintsForm,constraintsBody,fillConstraints} from '../../api/governance';import ConstraintsForm from '../../components/ConstraintsForm.vue';
const auth=useAuthStore(),send=command(),rows=ref<Rule[]>([]),assets=ref<Row[]>([]),fields=ref<Row[]>([]),otherFields=ref<Row[]>([]),standards=ref<Standard[]>([]),selected=ref<Rule|null>(null),editing=ref<Snapshot|null>(null),error=ref(''),message=ref(''),busy=ref(false),page=ref(1),total=ref(0),keyword=ref('');
const identity=reactive({assetId:'',fieldId:'',code:'',ruleType:'COMPLETENESS'}),form=reactive({versionNo:1,standardVersionId:'',otherFieldId:'',operator:'EQUALS',reason:''}),constraints=reactive(constraintsForm());
async function load(){const p=await get<Page>('D18-API-018',{}, {page:String(page.value),size:'20',...(keyword.value?{keyword:keyword.value}:{})});rows.value=p.items as Rule[];total.value=p.total;if(selected.value)selected.value=await get<Rule>('D18-API-057',{id:selected.value.id})}
async function run(f:()=>Promise<unknown>){busy.value=true;error.value='';message.value='';try{await f();await load()}catch(e){error.value=errorText(e)}finally{busy.value=false}}
async function assetChanged(){identity.fieldId='';fields.value=identity.assetId?await get<Row[]>('D18-API-013',{id:identity.assetId}):[]}
function newVersion(){editing.value=null;Object.assign(form,{versionNo:(selected.value?.versions[0]?.versionNo||0)+1,standardVersionId:'',otherFieldId:'',operator:'EQUALS',reason:''});Object.assign(constraints,constraintsForm())}
function closeDetail(){selected.value=null;editing.value=null;form.reason=''}
async function select(r:Rule){selected.value=await get<Rule>('D18-API-057',{id:r.id});newVersion();if(auth.permissions.includes('asset:read'))otherFields.value=(await get<Row[]>('D18-API-013',{id:r.assetId})).filter(f=>f.id!==r.fieldId);if(auth.permissions.includes('standard:read'))standards.value=(await get<Page>('D18-API-015',{}, {orgId:r.orgId,status:'PUBLISHED',size:'100'})).items as Standard[]}
function edit(v:Snapshot){editing.value=v;form.standardVersionId=v.standardVersionId||'';form.reason='';form.otherFieldId=String(v.parameters?.otherFieldId||'');form.operator=String(v.parameters?.operator||'EQUALS');fillConstraints(constraints,v.parameters||{})}
function parameters(){const type=selected.value?.ruleType;if(type==='VALIDITY')return form.standardVersionId?{}:constraintsBody(constraints);if(type==='COMPLETENESS')return {trim:constraints.trim};const p={trim:constraints.trim,ignoreCase:constraints.ignoreCase,allowNull:constraints.allowNull};return type==='CONSISTENCY'?{...p,otherFieldId:form.otherFieldId,operator:form.operator}:p}
async function save(){if(!selected.value)return;const common={standardVersionId:form.standardVersionId||null,parameters:parameters()};if(editing.value)await send('D18-API-058',{id:editing.value.id},{...common,expectedVersion:editing.value.version,reason:form.reason});else await send('D18-API-019',{id:selected.value.id},{...common,versionNo:form.versionNo,expectedVersion:selected.value.version});await load();newVersion();message.value='规则草稿已保存'}
async function publish(v:Snapshot){if(!form.reason.trim())throw new Error('请先填写发布说明');await send('D18-API-059',{id:v.id},{expectedVersion:v.version,reason:form.reason});editing.value=null;message.value='规则快照已发布，可用于检测和工单追踪'}
onMounted(()=>run(async()=>{await load();if(auth.permissions.includes('asset:read'))assets.value=(await get<Page>('D18-API-010',{}, {status:'PUBLISHED',size:'100'})).items}));
</script>
<template><section><h2>质量规则</h2><p>规则绑定资产字段，发布版本保存参数与摘要。检测和工单始终使用指定快照。</p><p class="error" role="alert">{{error}}</p><p role="status">{{message}}</p><form class="actions" @submit.prevent="page=1;run(load)"><label>规则代码<input v-model="keyword" maxlength="64"></label><button :disabled="busy">查询</button></form><form v-if="auth.permissions.includes('rule:write')" @submit.prevent="run(async()=>{const {assetId,...b}=identity;const r=await send<Rule>('D18-API-056',{},b);identity.code='';await select(r)})"><h3>新增字段规则</h3><div class="columns"><label>已发布资产<select v-model="identity.assetId" required @change="run(assetChanged)"><option value="">请选择</option><option v-for="a in assets" :key="a.id" :value="a.id">{{a.name}}</option></select></label><label>目标字段<select v-model="identity.fieldId" required><option value="">请选择</option><option v-for="f in fields" :key="f.id" :value="f.id">{{f.displayName}} / {{f.fieldCode}}</option></select></label><label>规则代码<input v-model="identity.code" required maxlength="64" pattern="[A-Za-z][A-Za-z0-9_.-]*"></label><label>规则类型<select v-model="identity.ruleType"><option v-for="(label,key) in ruleTypes" :key="key" :value="key">{{label}}</option></select></label></div><button :disabled="busy">创建规则</button></form><table><thead><tr><th>代码</th><th>类型</th><th>资产 / 字段</th><th>操作</th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td>{{r.code}}</td><td>{{ruleTypes[r.ruleType]}}</td><td>{{r.assetName}} / {{r.fieldCode}}</td><td><button @click="run(()=>select(r))">查看版本</button></td></tr></tbody></table><p v-if="!rows.length">暂无质量规则。</p><div class="actions"><button :disabled="page<=1||busy" @click="page--;run(load)">上一页</button>第{{page}}页 · 共{{total}}项<button :disabled="page*20>=total||busy" @click="page++;run(load)">下一页</button></div>
<div v-if="selected" class="modal-backdrop" @click.self="closeDetail"><section class="modal-panel" role="dialog" aria-modal="true" aria-labelledby="rule-version-title" @keydown.esc="closeDetail"><div class="modal-header"><div><span class="eyebrow">RULE VERSION DETAIL</span><h2 id="rule-version-title">{{selected.code}} 的规则版本</h2></div><button class="close-button" aria-label="关闭规则版本" @click="closeDetail">×</button></div><table><thead><tr><th>版本</th><th>状态</th><th>参数与摘要</th><th>操作</th></tr></thead><tbody><tr v-for="v in selected.versions" :key="v.id"><td>V{{v.versionNo}}</td><td>{{versionStates[v.status]}}</td><td><details><summary>查看快照</summary><pre>{{JSON.stringify(v.parameters,null,2)}}</pre><code>{{v.contentHash}}</code></details></td><td><button v-if="v.status==='DRAFT'&&auth.permissions.includes('rule:write')" @click="edit(v)">编辑</button><button v-if="v.status==='DRAFT'&&auth.permissions.includes('rule:publish')" :disabled="busy" @click="run(()=>publish(v))">发布</button></td></tr></tbody></table><label v-if="auth.permissions.includes('rule:write')||auth.permissions.includes('rule:publish')">修改或发布说明<textarea v-model="form.reason" maxlength="1000" placeholder="修改和发布前填写说明"/></label><form v-if="auth.permissions.includes('rule:write')" @submit.prevent="run(save)"><h3>{{editing?'编辑草稿':'新增规则版本'}}</h3><p v-if="!editing">新版本 V{{form.versionNo}}</p><template v-if="selected.ruleType==='VALIDITY'"><label>继承数据标准<select v-model="form.standardVersionId"><option value="">使用本规则约束</option><optgroup v-for="s in standards" :key="s.id" :label="s.name"><option v-for="v in s.versions.filter(v=>v.status==='PUBLISHED')" :key="v.id" :value="v.id">{{s.code}} V{{v.versionNo}}</option></optgroup></select></label><p v-if="form.standardVersionId">完整继承该发布标准的约束，并固定到规则快照。</p><ConstraintsForm v-else :form="constraints"/></template><template v-else><label class="check"><input v-model="constraints.trim" type="checkbox">忽略文本首尾空白</label><template v-if="selected.ruleType!=='COMPLETENESS'"><label class="check"><input v-model="constraints.allowNull" type="checkbox">允许空值</label><label class="check"><input v-model="constraints.ignoreCase" type="checkbox">忽略文本大小写</label></template><template v-if="selected.ruleType==='UNIQUENESS'"><p>在本次提交的数据集内检查；重复组内的所有记录均计为失败，不代表全库唯一。</p></template><template v-if="selected.ruleType==='CONSISTENCY'"><label>同资产对照字段<select v-model="form.otherFieldId" required><option value="">请选择</option><option v-for="f in otherFields" :key="f.id" :value="f.id">{{f.displayName}} / {{f.fieldCode}}</option></select></label><label>比较方式<select v-model="form.operator"><option value="EQUALS">应相等</option><option value="NOT_EQUALS">应不相等</option></select></label></template></template><button :disabled="busy">保存草稿</button><button type="button" @click="newVersion">新增版本</button></form></section></div></section></template>
<style scoped>
.modal-backdrop{position:fixed;inset:0;z-index:1000;display:grid;place-items:center;padding:24px;background:rgba(2,12,27,.78);backdrop-filter:blur(7px)}
.modal-panel{width:min(980px,100%);max-height:calc(100vh - 48px);overflow:auto;padding:26px;border:1px solid #2f77a8;border-radius:14px;background:linear-gradient(145deg,#09233f,#07182d);box-shadow:0 22px 70px rgba(0,0,0,.52)}
.modal-header{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}.modal-header h2{margin:4px 0 18px}.close-button{min-width:38px;height:38px;padding:0;font-size:26px;line-height:1}.modal-panel table{min-width:720px}.modal-panel code{display:block;max-width:320px;word-break:break-all}.modal-panel pre{margin:10px 0;white-space:pre-wrap}
@media (max-width:720px){.modal-backdrop{padding:10px}.modal-panel{max-height:calc(100vh - 20px);padding:18px}.modal-panel table{min-width:620px}}
</style>
