package com.example.datagov.modules.quality.application;
import com.example.datagov.common.*;
import org.springframework.stereotype.Service;import com.example.datagov.infrastructure.*;import com.example.datagov.infrastructure.idempotency.CommandExecutor;import com.example.datagov.modules.audit.application.AuditWriter;import com.example.datagov.security.*;import java.util.*;import static com.example.datagov.common.Checks.*;
/** D15-M04: manual intake and shared candidate decisions. DetectionService owns submitted-data execution. */
@Service public class QualityService {
 private final Db db;private final ScopePolicy scope;private final CommandExecutor commands;private final JsonSupport json;private final AuditWriter audit;
 public QualityService(Db db,ScopePolicy scope,CommandExecutor commands,JsonSupport json,AuditWriter audit){this.db=db;this.scope=scope;this.commands=commands;this.json=json;this.audit=audit;}
 public Object list(String table,String org,int page,int size){PrincipalContext.current().permission("quality:read");Db.paging(page,size);require(Set.of("quality_issue","detection_batch").contains(table),400,ErrorCode.INVALID_REQUEST,"查询无效");var ids=org==null?PrincipalContext.current().orgScopes():Set.of(id(org));if(org!=null)scope.org(org);if(ids.isEmpty())return Db.page(List.of(),page,size,0);List<Object> args=new ArrayList<>(ids);String where="org_id IN ("+String.join(",",Collections.nCopies(ids.size(),"?"))+")";long total=db.count("SELECT COUNT(*) FROM "+table+" WHERE "+where,args.toArray());args.add(size);args.add((page-1)*size);if("quality_issue".equals(table))return Db.page(db.list("SELECT q.*,w.id AS active_work_order_id,w.order_no AS active_work_order_no FROM quality_issue q LEFT JOIN governance_work_order w ON w.active_issue_id=q.id WHERE q."+where+" ORDER BY q.id DESC LIMIT ? OFFSET ?",args.toArray()),page,size,total);return Db.page(db.list("SELECT * FROM "+table+" WHERE "+where+" ORDER BY id DESC LIMIT ? OFFSET ?",args.toArray()),page,size,total);}
 public Object detail(String issue){PrincipalContext.current().permission("quality:read");var row=db.one("SELECT * FROM quality_issue WHERE id=?",id(issue));scope.org(Db.str(row,"org_id"));return Db.dto(row);}
 public Object batch(String key,String org,String rule,String no,String sourceType,Object body){return commands.execute("quality:register",key,body,()->{
  scope.org(id(org));require(sourceType!=null&&Set.of("MANUAL","ENGINE").contains(sourceType),400,ErrorCode.INVALID_REQUEST,"批次来源类型无效");if("ENGINE".equals(sourceType))PrincipalContext.current().permission("quality:execute");
  db.one("SELECT rv.id FROM rule_version rv JOIN quality_rule qr ON qr.id=rv.rule_id JOIN metadata_field f ON f.id=qr.field_id JOIN data_asset a ON a.id=f.asset_id WHERE rv.id=? AND qr.org_id=? AND rv.status='PUBLISHED' AND a.status='PUBLISHED'",id(rule),org);
  String bid=db.insert("INSERT INTO detection_batch(org_id,batch_no,rule_version_id,source_type,status,created_by) VALUES(?,?,?,?,'REGISTERED',?)",org,text(no,64),rule,sourceType,PrincipalContext.current().id());audit.write(org,"BATCH_REGISTER","detection_batch",bid,null,Map.of("ruleVersionId",rule,"sourceType",sourceType),"登记质量批次");return Db.dto(db.one("SELECT * FROM detection_batch WHERE id=?",bid));});}
 public Object register(String key,String org,String asset,String field,String rule,String batch,String summary,Map<String,Object> locator,Object body){return commands.execute("quality:register",key,body,()->{scope.org(id(org));db.one("SELECT id FROM data_asset WHERE id=? AND org_id=? AND status='PUBLISHED'",id(asset),org);db.one("SELECT f.id FROM metadata_field f JOIN data_asset a ON a.id=f.asset_id WHERE f.id=? AND f.asset_id=? AND a.org_id=?",id(field),asset,org);db.one("SELECT rv.id FROM rule_version rv JOIN quality_rule qr ON qr.id=rv.rule_id WHERE rv.id=? AND qr.org_id=? AND rv.status='PUBLISHED'",id(rule),org);db.one("SELECT rv.id FROM rule_version rv JOIN quality_rule qr ON qr.id=rv.rule_id WHERE rv.id=? AND qr.field_id=?",rule,field);db.one("SELECT id FROM detection_batch WHERE id=? AND org_id=? AND rule_version_id=? AND source_type='MANUAL' AND status='REGISTERED'",id(batch),org,rule);require(locator!=null&&locator.size()>=1&&locator.size()<=10,400,ErrorCode.INVALID_REQUEST,"必须提供异常定位信息");for(var e:locator.entrySet()){text(e.getKey(),64);require(e.getValue() instanceof String,400,ErrorCode.INVALID_REQUEST,"定位值必须为文本");text((String)e.getValue(),256);}String loc=json.canonical(locator);String fp=sha256((org+"\n"+asset+"\n"+field+"\n"+rule+"\n"+loc).getBytes(java.nio.charset.StandardCharsets.UTF_8));String issue=db.insert("INSERT INTO quality_issue(org_id,asset_id,field_id,rule_version_id,batch_id,issue_no,summary,fingerprint,status,locator_json,created_by) VALUES(?,?,?,?,?,?,?,?,'CANDIDATE',?,?)",org,asset,field,rule,batch,"QI-"+UUID.randomUUID(),text(summary,1000),fp,loc,PrincipalContext.current().id());audit.write(org,"ISSUE_REGISTER","quality_issue",issue,null,Map.of("fingerprint",fp),"登记异常候选");return Db.dto(db.one("SELECT * FROM quality_issue WHERE id=?",issue));});}
 public Object decision(String key,String issue,long expected,String decision,String related,String reason,Object body){return commands.execute("quality:decide",key,body,()->{var q=db.one("SELECT * FROM quality_issue WHERE id=? FOR UPDATE",id(issue));String org=Db.str(q,"org_id");scope.org(org);version(Db.num(q,"version"),expected);require("CANDIDATE".equals(q.get("status")),409,ErrorCode.STATE_CONFLICT,"仅候选问题可以判断");text(reason,1000);require("CONFIRM".equals(decision)||"MERGE".equals(decision),422,ErrorCode.INVALID_ASSOCIATION,"复开及其他判断规则未启用");db.update("INSERT INTO issue_identity(org_id,fingerprint) VALUES(?,?) ON DUPLICATE KEY UPDATE fingerprint=VALUES(fingerprint)",org,Db.str(q,"fingerprint"));var identity=db.one("SELECT * FROM issue_identity WHERE org_id=? AND fingerprint=? FOR UPDATE",org,Db.str(q,"fingerprint"));String active=Db.str(identity,"active_issue_id");String next;String target=related;
  if("CONFIRM".equals(decision)){require(active==null,409,ErrorCode.STATE_CONFLICT,"相同定位已有未闭环问题，请合并");next="CONFIRMED";db.update("UPDATE issue_identity SET active_issue_id=?,version=version+1 WHERE id=?",issue,Db.str(identity,"id"));target=null;}
  else{require(active!=null&&active.equals(related)&&!issue.equals(related),422,ErrorCode.INVALID_ASSOCIATION,"合并必须指向同定位的未闭环问题");next="MERGED";}
  db.update("UPDATE quality_issue SET status=?,related_issue_id=?,decision_reason=?,version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=?",next,target,reason,issue);audit.write(org,"ISSUE_"+decision,"quality_issue",issue,Map.of("status","CANDIDATE"),Map.of("status",next),reason);return Db.dto(db.one("SELECT * FROM quality_issue WHERE id=?",issue));});}
}
