<script setup lang="ts">
// FR-AUTH-001 / D18-API-005..009 / TC-AUTH-002/003/004
import {ref,reactive,onMounted,computed} from 'vue';import {useAuthStore} from '../../stores/auth';import {get,command,errorText,type Row,type Page,type Scope} from '../../api/implemented';
const auth=useAuthStore(),canGrant=computed(()=>auth.permissions.includes('auth:grant'));const orgs=ref<Row[]>([]),users=ref<Row[]>([]),error=ref(''),message=ref(''),busy=ref(false),page=ref(1),total=ref(0);const send=command();
const org=reactive({code:'',name:'',parentId:''}),user=reactive({orgId:'',username:'',displayName:'',password:''});const selected=ref<Row|null>(null),roleIds=ref<string[]>([]),scopeOrg=ref(''),scopeType=ref('ORG'),descendants=ref(false);
async function load(){orgs.value=await get<Row[]>('D18-API-005');const x=await get<Page>('D18-API-007',{}, {page:String(page.value),size:'20'});users.value=x.items;total.value=x.total;if(!org.parentId)org.parentId=orgs.value[0]?.id||'';if(!user.orgId)user.orgId=org.parentId}
async function run(action:()=>Promise<unknown>){busy.value=true;error.value='';message.value='';try{await action();message.value='操作成功';await load()}catch(e){error.value=errorText(e)}finally{busy.value=false}}
function select(u:Row){selected.value=u;roleIds.value=(u.roleIds||[]) as string[];const scopes=(u.scopes||[]) as Scope[];scopeOrg.value=scopes[0]?.orgId||String(u.orgId);scopeType.value=scopes[0]?.scopeType||'ORG';descendants.value=Boolean(scopes[0]?.includeDescendants)}
async function grants(){if(!selected.value)return;await send('D18-API-009',{id:selected.value.id},{expectedVersion:selected.value.version,roleIds:roleIds.value,scopes:[{orgId:scopeOrg.value,scopeType:scopeType.value,includeDescendants:descendants.value}]});selected.value=null}
onMounted(()=>run(load));
</script><template><section><h2>组织账号与权限管理</h2><p class="error" role="alert">{{error}}</p><p role="status">{{message}}</p><div v-if="canGrant" class="columns"><form @submit.prevent="run(()=>send('D18-API-006',{},org))"><h3>新增组织</h3><label>上级组织<select v-model="org.parentId"><option v-for="o in orgs" :value="o.id" :key="o.id">{{o.name}}</option></select></label><label>组织代码<input v-model="org.code" required maxlength="64"></label><label>组织名称<input v-model="org.name" required maxlength="128"></label><button :disabled="busy">创建组织</button></form><form @submit.prevent="run(async()=>{await send('D18-API-008',{},user);user.password=''})"><h3>新增账号</h3><label>所属组织<select v-model="user.orgId"><option v-for="o in orgs" :value="o.id" :key="o.id">{{o.name}}</option></select></label><label>账号<input v-model="user.username" required maxlength="64" autocomplete="off"></label><label>姓名<input v-model="user.displayName" required maxlength="64"></label><label>初始密码<input v-model="user.password" type="password" required minlength="12" autocomplete="new-password"></label><p>创建后需授予角色和组织范围，账号才能操作业务。</p><button :disabled="busy">创建账号</button></form></div><h3>账号列表</h3><table><thead><tr><th>姓名 / 账号</th><th>组织ID</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="u in users" :key="u.id"><td>{{u.displayName}} / {{u.username}}</td><td>{{u.orgId}}</td><td>{{u.status}}</td><td><button v-if="canGrant" @click="select(u)">编辑授权</button></td></tr></tbody></table><div class="actions"><button :disabled="page<=1||busy" @click="page--;run(load)">上一页</button><span>第{{page}}页 · 共{{total}}个账号</span><button :disabled="page*20>=total||busy" @click="page++;run(load)">下一页</button></div><form v-if="selected" @submit.prevent="run(grants)"><h3>替换 {{selected.displayName}} 的授权</h3><p>保存会使该账号的已有会话失效。当前表单将范围替换为下方的一条授权。</p><label v-for="r in auth.user?.roleCatalog||[]" :key="r.id" class="check"><input v-model="roleIds" type="checkbox" :value="r.id">{{r.name}}</label><label>授权组织<select v-model="scopeOrg"><option v-for="o in orgs" :value="o.id" :key="o.id">{{o.name}}</option></select></label><label>范围<select v-model="scopeType"><option value="ORG">组织业务</option><option value="ASSIGNED">本人分派及复检任务</option></select></label><label class="check"><input type="checkbox" v-model="descendants">包括子组织</label><button :disabled="busy">保存授权</button><button type="button" @click="selected=null">取消</button></form></section></template>