package com.example.datagov.modules.dashboard.application;
import com.example.datagov.common.*;
import com.example.datagov.infrastructure.Db;
import com.example.datagov.security.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.*;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.*;
import static com.example.datagov.common.Checks.*;

/** D15-M08. Facts from shared tables; unapproved ratio/duration definitions never masquerade as confirmed KPIs. */
@Service public class DashboardService {
 private final Db db;private final GovernanceWindow windows;private final JsonSupport json;
 public DashboardService(Db db,GovernanceWindow windows,JsonSupport json){this.db=db;this.windows=windows;this.json=json;}
 private static java.sql.Timestamp stamp(Instant t){return java.sql.Timestamp.from(t);}
 private long count(String table,String condition,GovernanceWindow.Window w){List<Object> args=new ArrayList<>();String scope=w.sql("a",args);args.add(stamp(w.asOf()));return db.count("SELECT COUNT(*) FROM "+table+" a WHERE "+scope+" AND a.created_at<=? AND "+condition,args.toArray());}
 private List<Map<String,Object>> closed(GovernanceWindow.Window w){List<Object> args=new ArrayList<>();String scope=w.sql("w",args);args.add(stamp(w.from()));args.add(stamp(w.to()));return db.list("SELECT w.id,w.order_no,w.due_at,w.closed_at,(SELECT MIN(h.created_at) FROM work_order_history h WHERE h.work_order_id=w.id AND h.action='CLAIM') AS claimed_at FROM governance_work_order w WHERE "+scope+" AND w.status='CLOSED' AND w.closed_at>=? AND w.closed_at<?",args.toArray());}
 private List<Map<String,Object>> firstReviews(GovernanceWindow.Window w){List<Object> args=new ArrayList<>();String scope=w.sql("w",args);args.add(stamp(w.from()));args.add(stamp(w.to()));return db.list("SELECT r.id,r.result,r.completed_at,t.work_order_id FROM review_result r JOIN review_task t ON t.id=r.task_id JOIN governance_work_order w ON w.id=t.work_order_id WHERE "+scope+" AND r.valid=1 AND r.result IN ('PASS','FAIL') AND r.completed_at>=? AND r.completed_at<? AND NOT EXISTS(SELECT 1 FROM review_result earlier JOIN review_task et ON et.id=earlier.task_id WHERE et.work_order_id=t.work_order_id AND earlier.valid=1 AND earlier.result IN ('PASS','FAIL') AND (earlier.completed_at<r.completed_at OR (earlier.completed_at=r.completed_at AND earlier.id<r.id)))",args.toArray());}
 private static Instant instant(Object v){if(v instanceof java.sql.Timestamp t)return t.toInstant();if(v instanceof LocalDateTime t)return t.toInstant(ZoneOffset.UTC);throw new IllegalArgumentException("Expected UTC database time");}
 private Map<String,Object> metric(String code,String name,String unit,BigDecimal numerator,long denominator,long excluded,String formula){
  Map<String,Object> out=new LinkedHashMap<>();out.put("code",code);out.put("name",name);out.put("unit",unit);out.put("numerator",numerator);out.put("denominator",denominator);out.put("excludedCount",excluded);out.put("formula",formula);out.put("metricVersion","V1");
  var definitions=db.list("SELECT version_no,status,definition_json FROM metric_definition WHERE code=? ORDER BY version_no DESC LIMIT 1",code);boolean confirmed=false;String reason="CANDIDATE_DEFINITION";
  if(!definitions.isEmpty()){var definition=definitions.get(0);out.put("definitionVersion",definition.get("version_no"));var body=json.parse(Db.str(definition,"definition_json"));confirmed="CONFIRMED".equals(definition.get("status"))&&Db.num(definition,"version_no")==1&&body instanceof Map<?,?> map&&code.equals(map.get("semanticKey"))&&"V1".equals(map.get("implementationVersion"));if("CONFIRMED".equals(definition.get("status"))&&!confirmed)reason="UNSUPPORTED_DEFINITION";}
  out.put("status",confirmed?"CONFIRMED":"CANDIDATE");if(denominator==0)reason="ZERO_DENOMINATOR";out.put("value",confirmed&&denominator>0?numerator.divide(BigDecimal.valueOf(denominator),4,RoundingMode.HALF_UP).multiply(unit.equals("%")?BigDecimal.valueOf(100):BigDecimal.ONE):null);out.put("reason",confirmed&&denominator>0?null:reason);return out;
 }
 @Transactional(readOnly=true) public Object metrics(Instant from,Instant to,Instant asOf,String org){
  PrincipalContext.current().permission("dashboard:read");var w=windows.resolve(from,to,asOf,org);var cards=new LinkedHashMap<String,Object>();
  cards.put("assetTotal",count("data_asset","1=1",w));cards.put("publishedAssetTotal",count("data_asset","status='PUBLISHED'",w));cards.put("openOrders",count("governance_work_order","status<>'CLOSED'",w));cards.put("waitingReviewOrders",count("governance_work_order","status='WAIT_REVIEW'",w));cards.put("openIssues",count("quality_issue","status IN ('CANDIDATE','CONFIRMED')",w));cards.put("candidateIssues",count("quality_issue","status='CANDIDATE'",w));
  List<Object> overdueArgs=new ArrayList<>();String os=w.sql("a",overdueArgs);overdueArgs.add(stamp(w.asOf()));overdueArgs.add(stamp(w.asOf()));cards.put("overdueOrders",db.count("SELECT COUNT(*) FROM governance_work_order a WHERE "+os+" AND a.created_at<=? AND a.status<>'CLOSED' AND a.due_at<?",overdueArgs.toArray()));
  List<Object> ruleArgs=new ArrayList<>();String rs=w.sql("q",ruleArgs);ruleArgs.add(stamp(w.asOf()));cards.put("publishedRuleVersions",db.count("SELECT COUNT(*) FROM rule_version rv JOIN quality_rule q ON q.id=rv.rule_id WHERE "+rs+" AND rv.status='PUBLISHED' AND rv.created_at<=?",ruleArgs.toArray()));
  List<Object> batchArgs=new ArrayList<>();String bs=w.sql("b",batchArgs);batchArgs.add(stamp(w.from()));batchArgs.add(stamp(w.to()));var scan=db.one("SELECT COUNT(*) AS completed_batches,COALESCE(SUM(scanned_count),0) AS scanned_records,COALESCE(SUM(failed_count),0) AS failed_records FROM detection_batch b WHERE "+bs+" AND b.source_type='ENGINE' AND b.status='SUCCEEDED' AND b.ended_at>=? AND b.ended_at<?",batchArgs.toArray());cards.put("completedBatches",scan.get("completed_batches"));cards.put("scannedRecords",scan.get("scanned_records"));cards.put("failedRecords",scan.get("failed_records"));
  var closed=closed(w);long dueCount=0,onTime=0,measured=0;BigDecimal hours=BigDecimal.ZERO;
  for(var c:closed){Instant end=instant(c.get("closed_at"));if(c.get("due_at")!=null){dueCount++;if(!end.isAfter(instant(c.get("due_at"))))onTime++;}if(c.get("claimed_at")!=null&&!end.isBefore(instant(c.get("claimed_at")))){measured++;hours=hours.add(BigDecimal.valueOf(Duration.between(instant(c.get("claimed_at")),end).toMillis()).divide(BigDecimal.valueOf(3600000),6,RoundingMode.HALF_UP));}}
  var reviews=firstReviews(w);long pass=reviews.stream().filter(r->"PASS".equals(r.get("result"))).count();cards.put("closedOrdersInWindow",closed.size());cards.put("firstBusinessReviews",reviews.size());
  var ratios=List.of(metric("ONTIME_CLOSE_RATE","按期关闭率","%",BigDecimal.valueOf(onTime),dueCount,closed.size()-dueCount,"窗口内有截止时间且closedAt≤dueAt的已关闭工单 / 窗口内有截止时间的已关闭工单"),metric("AVG_PROCESSING_HOURS","平均处理时长","小时",hours,measured,closed.size()-measured,"窗口内已关闭工单的首次认领至关闭总小时 / 有完整且非负时间记录的已关闭工单数"),metric("FIRST_REVIEW_PASS_RATE","复检一次通过率","%",BigDecimal.valueOf(pass),reviews.size(),0,"窗口内首次有效业务复检为PASS的工单 / 首次有效业务复检完成的工单，ERROR不计"));
  List<Object> statusArgs=new ArrayList<>();String ss=w.sql("a",statusArgs);statusArgs.add(stamp(w.asOf()));var statuses=db.list("SELECT status,COUNT(*) AS count FROM governance_work_order a WHERE "+ss+" AND a.created_at<=? GROUP BY status",statusArgs.toArray());
  List<Object> classArgs=new ArrayList<>();String cs=w.sql("a",classArgs);classArgs.add(stamp(w.asOf()));var classifications=db.list("SELECT classification,COUNT(*) AS count FROM data_asset a WHERE "+cs+" AND a.created_at<=? GROUP BY classification",classArgs.toArray());
  return Map.of("window",w.dto(),"generatedAt",Instant.now().toString(),"stateMode","CURRENT_STATE_AT_QUERY_TIME","cards",cards,"metrics",ratios,"orderStates",statuses.stream().map(Db::dto).toList(),"assetClasses",classifications.stream().map(Db::dto).toList(),"trend",trend(w),"metricVersion","V1");
 }
 private List<Map<String,Object>> trend(GovernanceWindow.Window w){
  Map<String,Map<String,Object>> days=new LinkedHashMap<>();for(LocalDate d=w.from().atOffset(ZoneOffset.UTC).toLocalDate();!d.isAfter(w.to().minusNanos(1).atOffset(ZoneOffset.UTC).toLocalDate());d=d.plusDays(1)){Map<String,Object> row=new LinkedHashMap<>();row.put("date",d.toString());for(String key:List.of("issues","closed","batches","scanned","failed"))row.put(key,0L);days.put(d.toString(),row);}
  for(String type:List.of("issues","closed","batches")){String table=type.equals("issues")?"quality_issue":type.equals("closed")?"governance_work_order":"detection_batch",time=type.equals("issues")?"created_at":type.equals("closed")?"closed_at":"ended_at",condition=type.equals("issues")?"1=1":type.equals("closed")?"status='CLOSED'":"source_type='ENGINE' AND status='SUCCEEDED'";List<Object> args=new ArrayList<>();String s=w.sql("a",args);args.add(stamp(w.from()));args.add(stamp(w.to()));var rows=db.list("SELECT DATE("+time+") AS day,COUNT(*) AS count"+(type.equals("batches")?",COALESCE(SUM(scanned_count),0) AS scanned,COALESCE(SUM(failed_count),0) AS failed":"")+" FROM "+table+" a WHERE "+s+" AND "+condition+" AND "+time+">=? AND "+time+"<? GROUP BY DATE("+time+")",args.toArray());for(var row:rows){var day=days.get(row.get("day").toString());if(day!=null){day.put(type,row.get("count"));if(type.equals("batches")){day.put("scanned",row.get("scanned"));day.put("failed",row.get("failed"));}}}}
  return new ArrayList<>(days.values());
 }
 @Transactional(readOnly=true) public Object drilldown(String code,String metricVersion,Instant from,Instant to,Instant asOf,String org,int page,int size){
  PrincipalContext.current().permission("dashboard:read");Db.paging(page,size);require("V1".equals(metricVersion),409,ErrorCode.VERSION_CONFLICT,"指标实现版本已变化，请刷新看板");var w=windows.resolve(from,to,asOf,org);String table,columns,condition,time;List<Object> args=new ArrayList<>();String scope=w.sql("a",args);
  switch(code){
   case "ASSETS"->{table="data_asset";columns="a.id,a.asset_code,a.name,a.status,a.classification,a.created_at";condition="1=1";time="snapshot";}
   case "OPEN_ISSUES"->{table="quality_issue";columns="a.id,a.issue_no,a.status,a.asset_id,a.field_id,a.created_at";condition="a.status IN ('CANDIDATE','CONFIRMED')";time="snapshot";}
   case "DETECTION_BATCHES"->{table="detection_batch";columns="a.id,a.batch_no,a.status,a.rule_version_id,a.scanned_count,a.failed_count,a.ended_at";condition="a.source_type='ENGINE' AND a.status='SUCCEEDED'";time="ended_at";}
   case "OPEN_ORDERS","WAIT_REVIEW_ORDERS","OVERDUE_OPEN_ORDERS","ONTIME_CLOSE_RATE","AVG_PROCESSING_HOURS","FIRST_REVIEW_PASS_RATE"->{table="governance_work_order";columns="a.id,a.order_no,a.status,a.current_round,a.due_at,a.closed_at,a.created_at";time="snapshot";condition=switch(code){case "OPEN_ORDERS"->"a.status<>'CLOSED'";case "WAIT_REVIEW_ORDERS"->"a.status='WAIT_REVIEW'";case "OVERDUE_OPEN_ORDERS"->{args.add(stamp(w.asOf()));yield "a.status<>'CLOSED' AND a.due_at<?";}default->"1=1";};
    if(Set.of("ONTIME_CLOSE_RATE","AVG_PROCESSING_HOURS","FIRST_REVIEW_PASS_RATE").contains(code)){List<String> ids=code.equals("FIRST_REVIEW_PASS_RATE")?firstReviews(w).stream().map(r->Db.str(r,"work_order_id")).toList():closed(w).stream().filter(r->code.equals("ONTIME_CLOSE_RATE")?r.get("due_at")!=null:r.get("claimed_at")!=null&&!instant(r.get("closed_at")).isBefore(instant(r.get("claimed_at")))).map(r->Db.str(r,"id")).toList();condition=ids.isEmpty()?"1=0":"a.id IN ("+String.join(",",Collections.nCopies(ids.size(),"?"))+")";args.addAll(ids);}
   }
   default->throw new BusinessException(ErrorCode.INVALID_REQUEST,400,"不支持的指标下钻代码");
  }
  String where=scope+" AND "+condition;if(time.equals("snapshot")){where+=" AND a.created_at<=?";args.add(stamp(w.asOf()));}else{where+=" AND a."+time+">=? AND a."+time+"<?";args.add(stamp(w.from()));args.add(stamp(w.to()));}long total=db.count("SELECT COUNT(*) FROM "+table+" a WHERE "+where,args.toArray());args.add(size);args.add((page-1)*size);
  return Map.of("items",db.list("SELECT "+columns+" FROM "+table+" a WHERE "+where+" ORDER BY a.id DESC LIMIT ? OFFSET ?",args.toArray()).stream().map(Db::dto).toList(),"page",page,"size",size,"total",total,"window",w.dto(),"metricCode",code,"metricVersion","V1");
 }
}
