package com.example.datagov.modules.workorder.application;
import com.example.datagov.common.*;
import com.example.datagov.infrastructure.Db;
import com.example.datagov.infrastructure.idempotency.CommandExecutor;
import com.example.datagov.modules.audit.application.AuditWriter;
import com.example.datagov.modules.workorder.domain.WorkOrderPolicy;
import com.example.datagov.security.*;
import org.springframework.stereotype.Service;
import java.time.*;
import java.util.*;
import static com.example.datagov.common.Checks.*;
import static com.example.datagov.modules.workorder.domain.WorkOrderPolicy.*;

/** D15-M05; commands always use locked resources and transaction-bound audit. */
@Service public class WorkorderService {
 private final Db db;private final ScopePolicy scope;private final CommandExecutor commands;private final AuditWriter audit;private final com.example.datagov.modules.evidence.application.FileStorage files;
 public WorkorderService(Db db,ScopePolicy scope,CommandExecutor commands,AuditWriter audit,com.example.datagov.modules.evidence.application.FileStorage files) { this.db=db;this.scope=scope;this.commands=commands;this.audit=audit;this.files=files; }
 public Map<String,Object> load(String orderId,boolean lock) { id(orderId);var w=db.one("SELECT * FROM governance_work_order WHERE id=?"+(lock?" FOR UPDATE":""),orderId);scope.order(w);return w; }
 public Object list(String status,String assigneeId,Boolean overdue,int page,int size) { var p=PrincipalContext.current();p.permission("workorder:read");Db.paging(page,size);List<Object> args=new ArrayList<>();String where=scope.orderSql(p,args);if(status!=null){require(Set.of("WAIT_DISPATCH","WAIT_CLAIM","PROCESSING","WAIT_REVIEW","CLOSED").contains(status),400,ErrorCode.INVALID_REQUEST,"工单状态无效");where+=" AND w.status=?";args.add(status);}if(assigneeId!=null){where+=" AND w.assignee_id=?";args.add(id(assigneeId));}if(overdue!=null)where+=" AND COALESCE((w.status<>'CLOSED' AND w.due_at<UTC_TIMESTAMP(3)),0)"+(overdue?"":"=0");long total=db.count("SELECT COUNT(*) FROM governance_work_order w WHERE "+where,args.toArray());args.add(size);args.add((page-1)*size);var rows=db.list("SELECT w.* FROM governance_work_order w WHERE "+where+" ORDER BY w.updated_at DESC,w.id DESC LIMIT ? OFFSET ?",args.toArray());return Map.of("items",rows.stream().map(this::present).toList(),"total",total,"page",page,"size",size); }
 public Object detail(String orderId) { PrincipalContext.current().permission("workorder:read");var w=load(orderId,false);var out=present(w);var submissions=db.list("SELECT * FROM remediation_round WHERE work_order_id=? ORDER BY round_no",orderId).stream().map(r->{var x=Db.dto(r);x.put("evidence",db.list("SELECT e.id,e.original_name,e.media_type,e.size_bytes,e.sha256 FROM round_evidence re JOIN evidence_file e ON e.id=re.evidence_id WHERE re.round_id=?",Db.str(r,"id")).stream().map(Db::dto).toList());return x;}).toList();out.put("submissions",submissions);out.put("reviewTasks",db.list("SELECT t.*,r.id AS result_id,r.result,r.reason,r.valid,r.proof_evidence_id FROM review_task t LEFT JOIN review_result r ON r.task_id=t.id WHERE t.work_order_id=? ORDER BY t.id",orderId).stream().map(Db::dto).toList());out.put("transferRequests",db.list("SELECT id,target_user_id,reason,status,requested_by FROM transfer_request WHERE work_order_id=? ORDER BY id DESC",orderId).stream().map(Db::dto).toList());return out; }
 private Map<String,Object> present(Map<String,Object> w) { var out=Db.dto(w);out.remove("activeIssueId");var p=PrincipalContext.current();String status=Db.str(w,"status");boolean overdue=false;var due=w.get("due_at");Instant dueInstant=due instanceof java.sql.Timestamp t?t.toInstant():due instanceof java.time.LocalDateTime t?t.toInstant(java.time.ZoneOffset.UTC):null;if(dueInstant!=null)overdue=!"CLOSED".equals(status)&&dueInstant.isBefore(Instant.now());out.put("overdue",overdue);out.put("coordinationRequired",Db.num(w,"coordination_required")==1);boolean close="WAIT_REVIEW".equals(status)&&w.get("valid_pass_id")!=null&&p.permissions().contains("workorder:close");out.put("canClose",close);List<String> actions=new ArrayList<>();if("WAIT_DISPATCH".equals(status)&&p.permissions().contains("workorder:dispatch"))actions.add("dispatch");boolean own=p.id().equals(Db.str(w,"assignee_id"));if("WAIT_CLAIM".equals(status)&&own&&p.permissions().contains("workorder:claim"))actions.add("claim");if("PROCESSING".equals(status)&&own&&p.permissions().contains("workorder:submit"))actions.add("submit");if(Set.of("WAIT_CLAIM","PROCESSING").contains(status)&&own&&p.permissions().contains("workorder:transfer"))actions.add("transfer");if("WAIT_REVIEW".equals(status)&&p.permissions().contains("review:execute")&&db.count("SELECT COUNT(*) FROM remediation_round WHERE work_order_id=? AND round_no=? AND submitted_by=?",Db.str(w,"id"),Db.num(w,"current_round"),p.id())==0)actions.add("review");if(close)actions.add("close");out.put("allowedActions",actions);return out; }
 public Object create(String key,String issueId,Object body) { return commands.execute("workorder:dispatch",key,body,()->{id(issueId);var issue=db.one("SELECT * FROM quality_issue WHERE id=? FOR UPDATE",issueId);scope.org(Db.str(issue,"org_id"));require("CONFIRMED".equals(issue.get("status")),422,ErrorCode.INVALID_ASSOCIATION,"仅已确认问题可以创建工单");require(db.count("SELECT COUNT(*) FROM governance_work_order WHERE active_issue_id=?",issueId)==0,409,ErrorCode.STATE_CONFLICT,"问题已有未关闭工单");String no="WO-"+UUID.randomUUID();String order=db.insert("INSERT INTO governance_work_order(org_id,issue_id,order_no,status,created_by) VALUES(?,?,?,'WAIT_DISPATCH',?)",Db.str(issue,"org_id"),issueId,no,PrincipalContext.current().id());var w=load(order,true);audit.history(w,null,"WAIT_DISPATCH","CREATE","创建待派发工单",null);audit.write(Db.str(w,"org_id"),"WORKORDER_CREATE","governance_work_order",order,null,Map.of("issueId",issueId,"status","WAIT_DISPATCH"),"创建工单");return present(w);}); }
 public void eligibleOwner(String userId,String org) { id(userId);var u=db.one("SELECT id,org_id FROM user_account WHERE id=? AND status='ENABLED'",userId);require(org.equals(Db.str(u,"org_id"))&&db.count("SELECT COUNT(*) FROM user_role ur JOIN role r ON r.id=ur.role_id JOIN role_permission rp ON rp.role_id=r.id JOIN permission p ON p.id=rp.permission_id WHERE ur.user_id=? AND r.status='ENABLED' AND p.code='workorder:claim'",userId)>0,422,ErrorCode.INVALID_ASSOCIATION,"责任人无效或不能认领");require(db.count("SELECT COUNT(*) FROM user_scope WHERE user_id=? AND org_id=?",userId,org)>0,422,ErrorCode.INVALID_ASSOCIATION,"责任人没有本组织授权范围"); }
 public Object dispatch(String key,String orderId,String assigneeId,Instant dueAt,String reason,long expected,Object body) { return commands.execute("workorder:dispatch",key,body,()->{var w=load(orderId,true);version(Db.num(w,"version"),expected);state(Db.str(w,"status"),"WAIT_DISPATCH");eligibleOwner(assigneeId,Db.str(w,"org_id"));require(dueAt!=null&&dueAt.isAfter(Instant.now()),422,ErrorCode.INVALID_REQUEST,"期限必须晚于当前时间");text(reason,1000);db.update("UPDATE governance_work_order SET assignee_id=?,due_at=?,status='WAIT_CLAIM',version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=?",assigneeId,java.sql.Timestamp.from(dueAt),orderId);event(w,"WAIT_CLAIM","DISPATCH",reason,null,Map.of("assigneeId",assigneeId,"dueAt",dueAt.toString()));return present(load(orderId,false));}); }
 public Object claim(String key,String orderId,long expected,Object body) { return commands.execute("workorder:claim",key,body,()->{var w=load(orderId,true);version(Db.num(w,"version"),expected);owner(PrincipalContext.current().id(),Db.str(w,"assignee_id"));state(Db.str(w,"status"),"WAIT_CLAIM");db.update("UPDATE governance_work_order SET status='PROCESSING',version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=?",orderId);event(w,"PROCESSING","CLAIM","责任人认领",null,null);return present(load(orderId,false));}); }
 public Object transfer(String key,String orderId,String target,String reason,long expected,Object body) { return commands.execute("workorder:transfer",key,body,()->{var w=load(orderId,true);version(Db.num(w,"version"),expected);owner(PrincipalContext.current().id(),Db.str(w,"assignee_id"));require(Set.of("WAIT_CLAIM","PROCESSING").contains(Db.str(w,"status")),409,ErrorCode.STATE_CONFLICT,"当前状态不能申请转派");eligibleOwner(target,Db.str(w,"org_id"));require(!target.equals(Db.str(w,"assignee_id")),422,ErrorCode.INVALID_ASSOCIATION,"转派目标不能为当前责任人");String request=db.insert("INSERT INTO transfer_request(work_order_id,requested_by,target_user_id,reason,status,created_by) VALUES(?,?,?,?,'PENDING',?)",orderId,PrincipalContext.current().id(),target,text(reason,1000),PrincipalContext.current().id());db.update("UPDATE governance_work_order SET coordination_required=1,version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=?",orderId);event(w,Db.str(w,"status"),"TRANSFER_REQUEST",reason,null,Map.of("requestId",request,"targetUserId",target));return Map.of("id",request,"status","PENDING","version",expected+1,"coordinationRequired",true);}); }
 public Object submit(String key,String orderId,int roundNo,long expected,String rootCause,String remediation,List<String> evidenceIds,Object body) { return commands.execute("workorder:submit",key,body,()->{var w=load(orderId,true);version(Db.num(w,"version"),expected);owner(PrincipalContext.current().id(),Db.str(w,"assignee_id"));state(Db.str(w,"status"),"PROCESSING");round(Db.num(w,"current_round"),roundNo);require(evidenceIds!=null&&evidenceIds.size()>=1&&evidenceIds.size()<=10&&new HashSet<>(evidenceIds).size()==evidenceIds.size(),400,ErrorCode.INVALID_REQUEST,"整改材料需为1至10份且不能重复");for(String e:evidenceIds)proof(e,orderId,PrincipalContext.current().id());String rule=Db.str(db.one("SELECT rule_version_id FROM quality_issue WHERE id=?",Db.str(w,"issue_id")),"rule_version_id");String submission=db.insert("INSERT INTO remediation_round(work_order_id,round_no,submitted_by,root_cause,remediation_text,submitted_at,submission_version,rule_version_id) VALUES(?,?,?,?,?,UTC_TIMESTAMP(3),?,?)",orderId,roundNo,PrincipalContext.current().id(),text(rootCause,4000),text(remediation,8000),expected+1,rule);for(String e:evidenceIds)db.update("INSERT INTO round_evidence(round_id,evidence_id,purpose) VALUES(?,?,'REMEDIATION')",submission,e);db.update("UPDATE governance_work_order SET status='WAIT_REVIEW',valid_pass_id=NULL,version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=?",orderId);event(w,"WAIT_REVIEW","SUBMIT","提交整改",null,Map.of("roundId",submission,"evidenceIds",evidenceIds));var out=present(load(orderId,false));out.put("roundId",submission);return out;}); }
 public Map<String,Object> proof(String evidence,String orderId,String uploader) { id(evidence);var file=db.one("SELECT * FROM evidence_file WHERE id=?",evidence);require(orderId.equals(Db.str(file,"work_order_id"))&&"READY".equals(file.get("status"))&&(uploader==null||uploader.equals(Db.str(file,"uploaded_by"))),422,ErrorCode.INVALID_PROOF,"材料必须为本工单的有效上传依据");files.verified(file);return file; }
 public Object close(String key,String orderId,int roundNo,long expected,String reviewResultId,String reason,Object body) { return commands.execute("workorder:close",key,body,()->{var w=load(orderId,true);version(Db.num(w,"version"),expected);state(Db.str(w,"status"),"WAIT_REVIEW");round(Db.num(w,"current_round"),roundNo);id(reviewResultId);require(reviewResultId.equals(Db.str(w,"valid_pass_id")),422,ErrorCode.INVALID_PROOF,"缺少当前轮次有效PASS");var r=db.one("SELECT r.*,t.work_order_id,t.round_id,t.rule_version_id,t.bound_work_order_version,t.requested_by,t.status AS task_status,s.round_no,s.submitted_by,s.rule_version_id AS submission_rule FROM review_result r JOIN review_task t ON t.id=r.task_id JOIN remediation_round s ON s.id=t.round_id WHERE r.id=?",reviewResultId);require(orderId.equals(Db.str(r,"work_order_id"))&&Db.num(r,"round_no")==roundNo&&Db.num(r,"valid")==1&&"PASS".equals(r.get("result"))&&"DONE".equals(r.get("task_status"))&&Db.num(r,"bound_work_order_version")+1==expected&&Db.str(r,"rule_version_id").equals(Db.str(r,"submission_rule")),422,ErrorCode.INVALID_PROOF,"PASS与当前轮次或版本不一致");independent(Db.str(r,"reviewer_id"),Db.str(r,"submitted_by"));proof(Db.str(r,"proof_evidence_id"),orderId,Db.str(r,"reviewer_id"));text(reason,1000);db.update("UPDATE governance_work_order SET status='CLOSED',closed_by=?,closed_at=UTC_TIMESTAMP(3),version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=?",PrincipalContext.current().id(),orderId);db.update("UPDATE quality_issue SET status='RESOLVED',version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=?",Db.str(w,"issue_id"));db.update("UPDATE issue_identity SET active_issue_id=NULL,version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE active_issue_id=?",Db.str(w,"issue_id"));event(w,"CLOSED","CLOSE",reason,reviewResultId,Map.of("reviewResultId",reviewResultId,"roundNo",roundNo,"submittedBy",Db.str(r,"submitted_by"),"reviewerId",Db.str(r,"reviewer_id"),"ruleVersionId",Db.str(r,"rule_version_id")));return present(load(orderId,false));}); }
 public void event(Map<String,Object> w,String next,String action,String reason,String review,Object extras) { String old=Db.str(w,"status");audit.history(w,old,next,action,reason,review);Map<String,Object> after=new LinkedHashMap<>();after.put("status",next);after.put("version",Db.num(w,"version")+("REVIEW_TASK".equals(action)?0:1));if(extras!=null)after.put("details",extras);audit.write(Db.str(w,"org_id"),"WORKORDER_"+action,"governance_work_order",Db.str(w,"id"),Map.of("status",old,"version",Db.num(w,"version")),after,reason); }
 public Object history(String orderId,int page,int size) { PrincipalContext.current().permission("workorder:read");load(orderId,false);Db.paging(page,size);return Db.page(db.list("SELECT * FROM work_order_history WHERE work_order_id=? ORDER BY created_at,id LIMIT ? OFFSET ?",orderId,size,(page-1)*size),page,size,db.count("SELECT COUNT(*) FROM work_order_history WHERE work_order_id=?",orderId)); }
 public Object pending(String api) { PrincipalContext.current().permission("workorder:approve-transfer");throw new BusinessException(ErrorCode.NOT_IMPLEMENTED,501,api+" 转派审批规则待确认，当前未开启"); }
}
