package com.example.datagov.modules.asset.application;
import com.example.datagov.common.*;
import org.springframework.stereotype.Service;
import com.example.datagov.infrastructure.Db;
import com.example.datagov.infrastructure.idempotency.CommandExecutor;
import com.example.datagov.modules.audit.application.AuditWriter;
import com.example.datagov.security.*;
import java.util.*;
import static com.example.datagov.common.Checks.*;
/** D15-M02; D17-T09/T10/T11. Manual metadata registration; no live source connection. */
@Service public class AssetService {
 private static final Set<String> CLASSIFICATIONS=Set.of("PUBLIC","INTERNAL","CONFIDENTIAL","RESTRICTED");
 private static final Set<String> TYPES=Set.of("VARCHAR","TEXT","INT","BIGINT","DECIMAL","DATE","DATETIME","BOOLEAN","JSON");
 private static final Set<String> SENSITIVITY=Set.of("LOW","MEDIUM","HIGH");
 private final Db db;private final ScopePolicy scope;private final CommandExecutor commands;private final AuditWriter audit;
 public AssetService(Db db,ScopePolicy scope,CommandExecutor commands,AuditWriter audit){this.db=db;this.scope=scope;this.commands=commands;this.audit=audit;}
 public record AssetInput(String orgId,String sourceId,String assetCode,String name,String classification,String ownerId){}
 public record AssetEdit(String name,String classification,String ownerId,String sourceId,long expectedVersion,String reason){}
 public record FieldInput(String fieldCode,String displayName,String dataType,Boolean nullable,String sensitiveLevel,long expectedAssetVersion){}
 public record FieldEdit(String displayName,String dataType,Boolean nullable,String sensitiveLevel,long expectedVersion,long expectedAssetVersion,String reason){}
 public record SourceInput(String orgId,String code,String sourceType,String endpointRef,String credentialRef){}
 public record SourceEdit(String endpointRef,String credentialRef,String status,long expectedVersion,String reason){}
 private static void enumValue(String value,Set<String> values){require(value!=null&&values.contains(value),400,ErrorCode.INVALID_REQUEST,"分类或元数据枚举无效");}
 private static String code(String value){String result=text(value,64);require(result.matches("[A-Za-z][A-Za-z0-9_.-]{0,63}"),400,ErrorCode.INVALID_REQUEST,"代码需以英文字母开头，仅含字母数字下划线点或短横线");return result;}
 private String filter(String alias,String org,List<Object> args){Set<String> ids=org==null?PrincipalContext.current().orgScopes():Set.of(id(org));if(org!=null)scope.org(org);if(ids.isEmpty())return "1=0";args.addAll(ids);return alias+".org_id IN ("+String.join(",",Collections.nCopies(ids.size(),"?"))+")";}
 private Map<String,Object> load(String asset,boolean lock){var row=db.one("SELECT * FROM data_asset WHERE id=?"+(lock?" FOR UPDATE":""),id(asset));scope.org(Db.str(row,"org_id"));return row;}
 private void owner(String user,String org){if(user!=null)db.one("SELECT id FROM user_account WHERE id=? AND org_id=? AND status='ENABLED'",id(user),org);}
 private void source(String source,String org){if(source!=null)db.one("SELECT id FROM data_source WHERE id=? AND org_id=? AND status='ENABLED' FOR UPDATE",id(source),org);}
 private Map<String,Object> present(Map<String,Object> asset){var out=Db.dto(asset);String assetId=Db.str(asset,"id"),status=Db.str(asset,"status");out.put("fieldCount",asset.containsKey("field_count")?Db.num(asset,"field_count"):db.count("SELECT COUNT(*) FROM metadata_field WHERE asset_id=?",assetId));List<String> actions=new ArrayList<>();if(PrincipalContext.current().permissions().contains("asset:write")){if(!"PUBLISHED".equals(status))actions.add("edit");if("PUBLISHED".equals(status))actions.add("disable");else actions.add("publish");if("DRAFT".equals(status))actions.add("registerField");}out.put("allowedActions",actions);return out;}
 public Object list(String org,String keyword,String status,String classification,String owner,int page,int size){PrincipalContext.current().permission("asset:read");Db.paging(page,size);List<Object> args=new ArrayList<>();String where=filter("a",org,args);if(keyword!=null&&!keyword.isBlank()){text(keyword,128);where+=" AND (LOCATE(?,a.asset_code)>0 OR LOCATE(?,a.name)>0)";args.add(keyword.strip());args.add(keyword.strip());}if(status!=null){enumValue(status,Set.of("DRAFT","PUBLISHED","DISABLED"));where+=" AND a.status=?";args.add(status);}if(classification!=null){enumValue(classification,CLASSIFICATIONS);where+=" AND a.classification=?";args.add(classification);}if(owner!=null){where+=" AND a.owner_id=?";args.add(id(owner));}long total=db.count("SELECT COUNT(*) FROM data_asset a WHERE "+where,args.toArray());args.add(size);args.add((page-1)*size);var rows=db.list("SELECT a.*,(SELECT COUNT(*) FROM metadata_field f WHERE f.asset_id=a.id) AS field_count,u.display_name AS owner_name,s.code AS source_code FROM data_asset a LEFT JOIN user_account u ON u.id=a.owner_id LEFT JOIN data_source s ON s.id=a.source_id WHERE "+where+" ORDER BY a.id DESC LIMIT ? OFFSET ?",args.toArray());return Map.of("items",rows.stream().map(this::present).toList(),"page",page,"size",size,"total",total);}
 public Object create(String key,AssetInput b){return commands.execute("asset:write",key,b,()->{String org=id(b.orgId());scope.org(org);db.one("SELECT id FROM org WHERE id=? AND status='ENABLED'",org);enumValue(b.classification(),CLASSIFICATIONS);owner(b.ownerId(),org);source(b.sourceId(),org);String asset=db.insert("INSERT INTO data_asset(org_id,source_id,asset_code,name,classification,owner_id,status,created_by) VALUES(?,?,?,?,?,?,'DRAFT',?)",org,b.sourceId(),code(b.assetCode()),text(b.name(),128),b.classification(),b.ownerId(),PrincipalContext.current().id());audit.write(org,"ASSET_CREATE","data_asset",asset,null,Map.of("assetCode",b.assetCode(),"status","DRAFT"),"登记资产草稿");return present(load(asset,false));});}
 public Object detail(String asset){PrincipalContext.current().permission("asset:read");var row=load(asset,false);var out=present(row);if(row.get("owner_id")!=null)out.put("owner",Db.dto(db.one("SELECT id,display_name,status FROM user_account WHERE id=?",Db.str(row,"owner_id"))));if(row.get("source_id")!=null)out.put("source",sourceView(db.one("SELECT * FROM data_source WHERE id=?",Db.str(row,"source_id"))));return out;}
 public Object edit(String key,String asset,AssetEdit b){return commands.execute("asset:write",key,b,()->{var row=load(asset,true);version(Db.num(row,"version"),b.expectedVersion());require(!"PUBLISHED".equals(row.get("status")),409,ErrorCode.STATE_CONFLICT,"已发布资产需先停用再编辑");text(b.reason(),1000);enumValue(b.classification(),CLASSIFICATIONS);owner(b.ownerId(),Db.str(row,"org_id"));source(b.sourceId(),Db.str(row,"org_id"));db.update("UPDATE data_asset SET name=?,classification=?,owner_id=?,source_id=?,version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=?",text(b.name(),128),b.classification(),b.ownerId(),b.sourceId(),asset);audit.write(Db.str(row,"org_id"),"ASSET_EDIT","data_asset",asset,Db.dto(row),Map.of("name",b.name(),"classification",b.classification()),b.reason());return present(load(asset,false));});}
 public Object state(String key,String asset,long expected,String next,String reason,Object body){return commands.execute("asset:write",key,body,()->{var row=load(asset,true);version(Db.num(row,"version"),expected);text(reason,1000);String org=Db.str(row,"org_id"),current=Db.str(row,"status");if("PUBLISHED".equals(next)){require(!"PUBLISHED".equals(current),409,ErrorCode.STATE_CONFLICT,"资产已经发布");require(row.get("owner_id")!=null,422,ErrorCode.INVALID_ASSOCIATION,"发布资产必须指定有效责任人");owner(Db.str(row,"owner_id"),org);source(Db.str(row,"source_id"),org);require(db.count("SELECT COUNT(*) FROM metadata_field WHERE asset_id=?",asset)>0,422,ErrorCode.INVALID_ASSOCIATION,"发布资产前至少登记一个字段");}else require("PUBLISHED".equals(current),409,ErrorCode.STATE_CONFLICT,"仅已发布资产可以停用");db.update("UPDATE data_asset SET status=?,version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=?",next,asset);audit.write(org,"ASSET_"+("PUBLISHED".equals(next)?"PUBLISH":"DISABLE"),"data_asset",asset,Map.of("status",current),Map.of("status",next),reason);return present(load(asset,false));});}
 public Object fields(String asset){PrincipalContext.current().permission("asset:read");load(asset,false);return db.list("SELECT f.*,(SELECT COUNT(DISTINCT r.id) FROM quality_rule r LEFT JOIN rule_version rv ON rv.rule_id=r.id WHERE r.field_id=f.id OR JSON_UNQUOTE(JSON_EXTRACT(rv.parameters,'$.otherFieldId'))=CAST(f.id AS CHAR)) AS rule_count,(SELECT COUNT(*) FROM field_standard s WHERE s.field_id=f.id) AS standard_count,(SELECT COUNT(*) FROM quality_issue q WHERE q.field_id=f.id) AS issue_count FROM metadata_field f WHERE f.asset_id=? ORDER BY f.id",asset).stream().map(Db::dto).toList();}
 private void fieldValues(String type,Boolean nullable,String sensitivity){enumValue(type,TYPES);enumValue(sensitivity,SENSITIVITY);require(nullable!=null,400,ErrorCode.INVALID_REQUEST,"必须明确字段是否可空");}
 public Object field(String key,String asset,FieldInput b){return commands.execute("asset:write",key,b,()->{var row=load(asset,true);version(Db.num(row,"version"),b.expectedAssetVersion());require("DRAFT".equals(row.get("status")),409,ErrorCode.STATE_CONFLICT,"仅草稿资产可新增字段");fieldValues(b.dataType(),b.nullable(),b.sensitiveLevel());String field=db.insert("INSERT INTO metadata_field(asset_id,field_code,display_name,data_type,nullable,sensitive_level,created_by) VALUES(?,?,?,?,?,?,?)",asset,code(b.fieldCode()),text(b.displayName(),128),b.dataType(),b.nullable()?1:0,b.sensitiveLevel(),PrincipalContext.current().id());db.update("UPDATE data_asset SET version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=?",asset);audit.write(Db.str(row,"org_id"),"FIELD_CREATE","metadata_field",field,null,Map.of("assetId",asset,"fieldCode",b.fieldCode()),"手工登记元数据字段");var out=Db.dto(db.one("SELECT * FROM metadata_field WHERE id=?",field));out.put("assetVersion",b.expectedAssetVersion()+1);return out;});}
 public Object editField(String key,String asset,String field,FieldEdit b){return commands.execute("asset:write",key,b,()->{var row=load(asset,true);version(Db.num(row,"version"),b.expectedAssetVersion());require(!"PUBLISHED".equals(row.get("status")),409,ErrorCode.STATE_CONFLICT,"已发布资产的字段不可直接修改");var f=db.one("SELECT * FROM metadata_field WHERE id=? AND asset_id=? FOR UPDATE",id(field),asset);version(Db.num(f,"version"),b.expectedVersion());fieldValues(b.dataType(),b.nullable(),b.sensitiveLevel());text(b.reason(),1000);boolean structural=!b.dataType().equals(f.get("data_type"))||(b.nullable()?1:0)!=Db.num(f,"nullable")||!b.sensitiveLevel().equals(f.get("sensitive_level"));if(structural)require(db.count("SELECT COUNT(DISTINCT r.id) FROM quality_rule r LEFT JOIN rule_version rv ON rv.rule_id=r.id WHERE r.field_id=? OR JSON_UNQUOTE(JSON_EXTRACT(rv.parameters,'$.otherFieldId'))=?",field,field)==0&&db.count("SELECT COUNT(*) FROM quality_issue WHERE field_id=?",field)==0&&db.count("SELECT COUNT(*) FROM field_standard WHERE field_id=?",field)==0,409,ErrorCode.STATE_CONFLICT,"字段已有规则、问题或标准关联，结构变更需新增资产版本，当前入口不支持");db.update("UPDATE metadata_field SET display_name=?,data_type=?,nullable=?,sensitive_level=?,version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=?",text(b.displayName(),128),b.dataType(),b.nullable()?1:0,b.sensitiveLevel(),field);db.update("UPDATE data_asset SET version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=?",asset);audit.write(Db.str(row,"org_id"),"FIELD_EDIT","metadata_field",field,Db.dto(f),Map.of("displayName",b.displayName(),"dataType",b.dataType()),b.reason());var out=Db.dto(db.one("SELECT * FROM metadata_field WHERE id=?",field));out.put("assetVersion",b.expectedAssetVersion()+1);return out;});}
 private Map<String,Object> sourceView(Map<String,Object> row){var out=Db.dto(row);out.remove("credentialRef");out.put("credentialConfigured",row.get("credential_ref")!=null);return out;}
 private String ref(String value,int max){if(value==null||value.isBlank())return null;String v=text(value,max);require(v.matches("[A-Za-z0-9_./:-]+"),400,ErrorCode.INVALID_REQUEST,"仅允许逻辑配置引用，不接受连接密码或URL参数");return v;}
 public Object sources(String org,String status,int page,int size){PrincipalContext.current().permission("asset:read");Db.paging(page,size);List<Object> args=new ArrayList<>();String where=filter("s",org,args);if(status!=null){enumValue(status,Set.of("ENABLED","DISABLED"));where+=" AND s.status=?";args.add(status);}long total=db.count("SELECT COUNT(*) FROM data_source s WHERE "+where,args.toArray());args.add(size);args.add((page-1)*size);return Map.of("items",db.list("SELECT * FROM data_source s WHERE "+where+" ORDER BY s.id DESC LIMIT ? OFFSET ?",args.toArray()).stream().map(this::sourceView).toList(),"page",page,"size",size,"total",total);}
 public Object createSource(String key,SourceInput b){return commands.execute("asset:write",key,b,()->{String org=id(b.orgId());scope.org(org);db.one("SELECT id FROM org WHERE id=? AND status='ENABLED'",org);enumValue(b.sourceType(),Set.of("MANUAL","MYSQL"));String endpoint=ref(b.endpointRef(),255),credential=ref(b.credentialRef(),128);require(!"MYSQL".equals(b.sourceType())||endpoint!=null,400,ErrorCode.INVALID_REQUEST,"MYSQL来源需提供逻辑连接配置引用");String source=db.insert("INSERT INTO data_source(org_id,code,source_type,endpoint_ref,credential_ref,status,created_by) VALUES(?,?,?,?,?,'ENABLED',?)",org,code(b.code()),b.sourceType(),endpoint,credential,PrincipalContext.current().id());audit.write(org,"SOURCE_CREATE","data_source",source,null,Map.of("code",b.code(),"sourceType",b.sourceType()),"登记来源元信息，未连接真实数据源");return sourceView(db.one("SELECT * FROM data_source WHERE id=?",source));});}
 public Object editSource(String key,String source,SourceEdit b){return commands.execute("asset:write",key,b,()->{var row=db.one("SELECT * FROM data_source WHERE id=? FOR UPDATE",id(source));scope.org(Db.str(row,"org_id"));version(Db.num(row,"version"),b.expectedVersion());enumValue(b.status(),Set.of("ENABLED","DISABLED"));text(b.reason(),1000);String endpoint=ref(b.endpointRef(),255),credential=b.credentialRef()==null?Db.str(row,"credential_ref"):ref(b.credentialRef(),128);require(!"MYSQL".equals(row.get("source_type"))||endpoint!=null,400,ErrorCode.INVALID_REQUEST,"MYSQL来源需保留逻辑配置引用");if("DISABLED".equals(b.status()))require(db.list("SELECT id FROM data_asset WHERE source_id=? AND status='PUBLISHED' FOR UPDATE",source).isEmpty(),409,ErrorCode.STATE_CONFLICT,"先停用该来源关联的已发布资产");db.update("UPDATE data_source SET endpoint_ref=?,credential_ref=?,status=?,version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=?",endpoint,credential,b.status(),source);audit.write(Db.str(row,"org_id"),"SOURCE_EDIT","data_source",source,Map.of("status",Db.str(row,"status")),Map.of("status",b.status()),b.reason());return sourceView(db.one("SELECT * FROM data_source WHERE id=?",source));});}
}
