package com.example.datagov.modules.standard.application;
import com.example.datagov.common.*;
import com.example.datagov.infrastructure.Db;
import com.example.datagov.infrastructure.idempotency.CommandExecutor;
import com.example.datagov.modules.audit.application.AuditWriter;
import com.example.datagov.modules.standard.domain.RulePolicy;
import com.example.datagov.security.*;
import org.springframework.stereotype.Service;
import java.util.*;
import static com.example.datagov.common.Checks.*;

/** D15-M03; D17-T13..T17. Published snapshots cannot be modified in place. */
@Service public class StandardService {
 private final Db db;private final ScopePolicy scope;private final CommandExecutor commands;private final JsonSupport json;private final AuditWriter audit;
 public StandardService(Db db,ScopePolicy scope,CommandExecutor commands,JsonSupport json,AuditWriter audit){this.db=db;this.scope=scope;this.commands=commands;this.json=json;this.audit=audit;}
 public record StandardInput(String orgId,String code,String name){}
 public record StandardVersionInput(int versionNo,Map<String,Object> definition,Long expectedVersion){}
 public record StandardEdit(Map<String,Object> definition,Long expectedVersion,String reason){}
 public record Publish(Long expectedVersion,String reason){}
 public record RuleInput(String fieldId,String code,String ruleType){}
 public record RuleVersionInput(int versionNo,String standardVersionId,Map<String,Object> parameters,Long expectedVersion){}
 public record RuleEdit(String standardVersionId,Map<String,Object> parameters,Long expectedVersion,String reason){}
 public record Binding(String standardVersionId,Long expectedAssetVersion,String reason){}
 private static long expected(Long n){require(n!=null&&n>=0,400,ErrorCode.INVALID_REQUEST,"必须提供对象版本");return n;}
 private static String code(String v){v=text(v,64);require(v.matches("[A-Za-z][A-Za-z0-9_.-]{0,63}"),400,ErrorCode.INVALID_REQUEST,"代码格式无效");return v;}
 private String filter(String org,List<Object> args){var ids=org==null?PrincipalContext.current().orgScopes():Set.of(id(org));if(org!=null)scope.org(org);if(ids.isEmpty())return "1=0";args.addAll(ids);return "s.org_id IN ("+String.join(",",Collections.nCopies(ids.size(),"?"))+")";}
 public Object list(boolean rules,String org,String field,String keyword,String status,int page,int size){
  PrincipalContext.current().permission(rules?"rule:read":"standard:read");Db.paging(page,size);List<Object> args=new ArrayList<>();String where=filter(org,args);
  if(keyword!=null){where+=" AND LOCATE(?,s.code)>0";args.add(text(keyword,64));}
  if(field!=null){field(field,false);if(rules){where+=" AND s.field_id=?";args.add(field);}else{where+=" AND EXISTS(SELECT 1 FROM field_standard fs JOIN standard_version sv ON sv.id=fs.standard_version_id WHERE fs.field_id=? AND sv.standard_id=s.id)";args.add(field);}}
  String identity=rules?"quality_rule":"data_standard",versions=rules?"rule_version":"standard_version",parent=rules?"rule_id":"standard_id";
  if(status!=null){require(Set.of("DRAFT","PUBLISHED","RETIRED").contains(status),400,ErrorCode.INVALID_REQUEST,"版本状态无效");where+=" AND EXISTS(SELECT 1 FROM "+versions+" v WHERE v."+parent+"=s.id AND v.status=?)";args.add(status);}
  long total=db.count("SELECT COUNT(*) FROM "+identity+" s WHERE "+where,args.toArray());args.add(size);args.add((page-1)*size);
  return Map.of("items",db.list("SELECT s.* FROM "+identity+" s WHERE "+where+" ORDER BY s.id DESC LIMIT ? OFFSET ?",args.toArray()).stream().map(r->present(r,rules)).toList(),"total",total,"page",page,"size",size);
 }
 private Map<String,Object> identity(String resource,boolean rules,boolean lock){var row=db.one("SELECT * FROM "+(rules?"quality_rule":"data_standard")+" WHERE id=?"+(lock?" FOR UPDATE":""),id(resource));scope.org(Db.str(row,"org_id"));return row;}
 private Map<String,Object> present(Map<String,Object> row,boolean rules){var out=Db.dto(row);String table=rules?"rule_version":"standard_version",fk=rules?"rule_id":"standard_id";out.put("versions",db.list("SELECT * FROM "+table+" WHERE "+fk+"=? ORDER BY version_no DESC",Db.str(row,"id")).stream().map(this::snapshot).toList());if(rules){var f=field(Db.str(row,"field_id"),false);out.put("fieldCode",f.get("field_code"));out.put("assetId",Db.str(f,"asset_id"));out.put("assetName",f.get("asset_name"));}return out;}
 private Map<String,Object> snapshot(Map<String,Object> row){var out=Db.dto(row);for(String k:List.of("definition","parameters"))if(out.get(k) instanceof String s)out.put(k,json.parse(s));return out;}
 public Object detail(String resource,boolean rules){PrincipalContext.current().permission(rules?"rule:read":"standard:read");return present(identity(resource,rules,false),rules);}
 private Map<String,Object> field(String fid,boolean lock){var f=db.one("SELECT f.*,a.org_id,a.status AS asset_status,a.name AS asset_name FROM metadata_field f JOIN data_asset a ON a.id=f.asset_id WHERE f.id=?"+(lock?" FOR UPDATE":""),id(fid));scope.org(Db.str(f,"org_id"));return f;}
 public Object createStandard(String key,StandardInput b){return commands.execute("standard:write",key,b,()->{scope.org(id(b.orgId()));String sid=db.insert("INSERT INTO data_standard(org_id,code,name,created_by) VALUES(?,?,?,?)",b.orgId(),code(b.code()),text(b.name(),128),PrincipalContext.current().id());audit.write(b.orgId(),"STANDARD_CREATE","data_standard",sid,null,Map.of("code",b.code()),"创建标准身份");return present(identity(sid,false,false),false);});}
 public Object createRule(String key,RuleInput b){return commands.execute("rule:write",key,b,()->{var f=field(b.fieldId(),true);require(!"DISABLED".equals(f.get("asset_status")),409,ErrorCode.STATE_CONFLICT,"停用资产不可新增规则");require(b.ruleType()!=null&&RulePolicy.TYPES.contains(b.ruleType()),400,ErrorCode.INVALID_REQUEST,"规则类型无效");String org=Db.str(f,"org_id");String rid=db.insert("INSERT INTO quality_rule(org_id,field_id,code,rule_type,created_by) VALUES(?,?,?,?,?)",org,b.fieldId(),code(b.code()),b.ruleType(),PrincipalContext.current().id());audit.write(org,"RULE_CREATE","quality_rule",rid,null,Map.of("fieldId",b.fieldId(),"ruleType",b.ruleType()),"创建规则身份");return present(identity(rid,true,false),true);});}
 private void sequence(String table,String parent,String resource,int no){require(no>=1&&no<=1000000,400,ErrorCode.INVALID_REQUEST,"版本号需为正整数");long last=db.count("SELECT COALESCE(MAX(version_no),0) FROM "+table+" WHERE "+parent+"=?",resource);require(no==last+1,409,ErrorCode.VERSION_CONFLICT,"业务版本号必须连续递增");}
 private void bump(String table,String resource){db.update("UPDATE "+table+" SET version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=?",resource);}
 public Object standardVersion(String key,String sid,StandardVersionInput b){return commands.execute("standard:write",key,b,()->{var s=identity(sid,false,true);version(Db.num(s,"version"),expected(b.expectedVersion()));sequence("standard_version","standard_id",sid,b.versionNo());String vid=db.insert("INSERT INTO standard_version(standard_id,version_no,definition,status,created_by) VALUES(?,?,?,'DRAFT',?)",sid,b.versionNo(),json.canonical(RulePolicy.definition(b.definition())),PrincipalContext.current().id());bump("data_standard",sid);audit.write(Db.str(s,"org_id"),"STANDARD_VERSION_CREATE","standard_version",vid,null,Map.of("versionNo",b.versionNo()),"新增标准草稿版本");return snapshot(db.one("SELECT * FROM standard_version WHERE id=?",vid));});}
 private Map<String,Object> versionRow(String vid,boolean rules){String table=rules?"rule_version":"standard_version",fk=rules?"rule_id":"standard_id";var row=db.one("SELECT * FROM "+table+" WHERE id=?",id(vid));identity(Db.str(row,fk),rules,true);return db.one("SELECT * FROM "+table+" WHERE id=? FOR UPDATE",vid);}
 private void draft(Map<String,Object> v,Long n){version(Db.num(v,"version"),expected(n));require("DRAFT".equals(v.get("status")),409,ErrorCode.STATE_CONFLICT,"仅草稿可修改或发布；发布快照不可原位修改");}
 public Object editStandard(String key,String vid,StandardEdit b){return commands.execute("standard:write",key,b,()->{var v=versionRow(vid,false);draft(v,b.expectedVersion());var s=identity(Db.str(v,"standard_id"),false,false);String definition=json.canonical(RulePolicy.definition(b.definition()));text(b.reason(),1000);db.update("UPDATE standard_version SET definition=?,version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=?",definition,vid);audit.write(Db.str(s,"org_id"),"STANDARD_VERSION_EDIT","standard_version",vid,null,Map.of("definitionHash",sha256(definition.getBytes(java.nio.charset.StandardCharsets.UTF_8))),b.reason());return snapshot(db.one("SELECT * FROM standard_version WHERE id=?",vid));});}
 public Object publishStandard(String key,String vid,Publish b){return commands.execute("standard:publish",key,b,()->{var v=versionRow(vid,false);draft(v,b.expectedVersion());RulePolicy.definition(RulePolicy.object(json.parse(Db.str(v,"definition"))));var s=identity(Db.str(v,"standard_id"),false,false);text(b.reason(),1000);db.update("UPDATE standard_version SET status='PUBLISHED',published_at=UTC_TIMESTAMP(3),version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=?",vid);audit.write(Db.str(s,"org_id"),"STANDARD_PUBLISH","standard_version",vid,Map.of("status","DRAFT"),Map.of("status","PUBLISHED"),b.reason());return snapshot(db.one("SELECT * FROM standard_version WHERE id=?",vid));});}
 private Map<String,Object> effective(Map<String,Object> r,String standard,Map<String,Object> params){String type=Db.str(r,"rule_type");Map<String,Object> result;if(standard!=null){require("VALIDITY".equals(type),400,ErrorCode.INVALID_REQUEST,"标准约束仅用于有效性规则");var sv=db.one("SELECT sv.* FROM standard_version sv JOIN data_standard s ON s.id=sv.standard_id WHERE sv.id=? AND s.org_id=? AND sv.status='PUBLISHED'",id(standard),Db.str(r,"org_id"));require(params!=null&&params.isEmpty(),400,ErrorCode.INVALID_REQUEST,"关联标准时参数需为空对象，完整继承约束");result=RulePolicy.parameters(type,RulePolicy.object(RulePolicy.object(json.parse(Db.str(sv,"definition"))).get("constraints")));}else result=RulePolicy.parameters(type,params);if(type.equals("CONSISTENCY")){var f=field(Db.str(r,"field_id"),false);var other=field((String)result.get("otherFieldId"),false);require(f.get("asset_id").equals(other.get("asset_id"))&&!Db.str(f,"id").equals(Db.str(other,"id")),400,ErrorCode.INVALID_ASSOCIATION,"对照字段必须为同资产的其他字段");}return result;}
 private String hash(Map<String,Object> r,String standard,Map<String,Object> params){Map<String,Object> content=new LinkedHashMap<>();content.put("fieldId",Db.str(r,"field_id"));content.put("ruleType",r.get("rule_type"));content.put("standardVersionId",standard);content.put("parameters",params);return sha256(json.canonical(content).getBytes(java.nio.charset.StandardCharsets.UTF_8));}
 public Object ruleVersion(String key,String rid,RuleVersionInput b){return commands.execute("rule:write",key,b,()->{var r=identity(rid,true,true);version(Db.num(r,"version"),expected(b.expectedVersion()));sequence("rule_version","rule_id",rid,b.versionNo());var p=effective(r,b.standardVersionId(),b.parameters());String vid=db.insert("INSERT INTO rule_version(rule_id,version_no,standard_version_id,parameters,content_hash,status,created_by) VALUES(?,?,?,?,?,'DRAFT',?)",rid,b.versionNo(),b.standardVersionId(),json.canonical(p),hash(r,b.standardVersionId(),p),PrincipalContext.current().id());bump("quality_rule",rid);audit.write(Db.str(r,"org_id"),"RULE_VERSION_CREATE","rule_version",vid,null,Map.of("contentHash",hash(r,b.standardVersionId(),p)),"新增规则草稿快照");return snapshot(db.one("SELECT * FROM rule_version WHERE id=?",vid));});}
 public Object editRule(String key,String vid,RuleEdit b){return commands.execute("rule:write",key,b,()->{var v=versionRow(vid,true);draft(v,b.expectedVersion());var r=identity(Db.str(v,"rule_id"),true,false);var p=effective(r,b.standardVersionId(),b.parameters());text(b.reason(),1000);String digest=hash(r,b.standardVersionId(),p);db.update("UPDATE rule_version SET standard_version_id=?,parameters=?,content_hash=?,version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=?",b.standardVersionId(),json.canonical(p),digest,vid);audit.write(Db.str(r,"org_id"),"RULE_VERSION_EDIT","rule_version",vid,null,Map.of("contentHash",digest),b.reason());return snapshot(db.one("SELECT * FROM rule_version WHERE id=?",vid));});}
 public Object publishRule(String key,String vid,Publish b){return commands.execute("rule:publish",key,b,()->{var v=versionRow(vid,true);draft(v,b.expectedVersion());var r=identity(Db.str(v,"rule_id"),true,false);var f=field(Db.str(r,"field_id"),true);require("PUBLISHED".equals(f.get("asset_status")),409,ErrorCode.STATE_CONFLICT,"资产发布后才可发布规则");var stored=RulePolicy.object(json.parse(Db.str(v,"parameters")));var p=effective(r,Db.str(v,"standard_version_id"),v.get("standard_version_id")==null?stored:Map.of());require(json.canonical(p).equals(json.canonical(stored))&&hash(r,Db.str(v,"standard_version_id"),p).equals(v.get("content_hash")),409,ErrorCode.STATE_CONFLICT,"快照摘要不匹配，请重建草稿");text(b.reason(),1000);db.update("UPDATE rule_version SET status='PUBLISHED',version=version+1,updated_at=UTC_TIMESTAMP(3) WHERE id=?",vid);audit.write(Db.str(r,"org_id"),"RULE_PUBLISH","rule_version",vid,Map.of("status","DRAFT"),Map.of("status","PUBLISHED","contentHash",v.get("content_hash")),b.reason());return snapshot(db.one("SELECT * FROM rule_version WHERE id=?",vid));});}
 public Object bind(String key,String fid,Binding b){return commands.execute("standard:write",key,b,()->{var f=field(fid,true);var a=db.one("SELECT * FROM data_asset WHERE id=? FOR UPDATE",Db.str(f,"asset_id"));version(Db.num(a,"version"),expected(b.expectedAssetVersion()));require(!"DISABLED".equals(a.get("status")),409,ErrorCode.STATE_CONFLICT,"停用资产不可追加标准映射");db.one("SELECT sv.id FROM standard_version sv JOIN data_standard s ON s.id=sv.standard_id WHERE sv.id=? AND s.org_id=? AND sv.status='PUBLISHED'",id(b.standardVersionId()),Db.str(f,"org_id"));text(b.reason(),1000);String bid=db.insert("INSERT INTO field_standard(field_id,standard_version_id) VALUES(?,?)",fid,b.standardVersionId());bump("data_asset",Db.str(f,"asset_id"));audit.write(Db.str(f,"org_id"),"FIELD_STANDARD_BIND","field_standard",bid,null,Map.of("fieldId",fid,"standardVersionId",b.standardVersionId()),b.reason());return Map.of("id",bid,"fieldId",fid,"standardVersionId",b.standardVersionId(),"assetVersion",Db.num(a,"version")+1);});}
}
