<script setup lang="ts">
import {onBeforeUnmount,onMounted,ref} from 'vue'
const errorMessage=ref('')
function showError(event:Event){errorMessage.value=String((event as CustomEvent<string>).detail||'操作失败')}
function dismiss(){errorMessage.value=''}
function closeBox(box:HTMLElement){const nativeClose=Array.from(box.querySelectorAll<HTMLButtonElement>('button')).find(button=>['收起','取消'].includes(button.textContent?.trim()||''));if(nativeClose){nativeClose.click();return}window.dispatchEvent(new Event('datagov:close-detail'));setTimeout(()=>{if(box.isConnected)box.style.display='none'},0)}
function addClose(box:HTMLElement){if(box.querySelector(':scope > .auto-detail-close'))return;const button=document.createElement('button');button.type='button';button.className='auto-detail-close';button.textContent='×';button.setAttribute('aria-label','关闭详情');button.addEventListener('click',()=>closeBox(box));box.prepend(button)}
onMounted(()=>{window.addEventListener('datagov:error',showError);const attach=()=>{document.querySelectorAll<HTMLElement>('main>section>div:has(>h3),main>section>article').forEach(addClose);document.querySelectorAll<HTMLElement>('main article h3').forEach(title=>{if(!['整改提交快照','复检记录'].includes(title.textContent?.trim()||''))return;const next=title.nextElementSibling;const empty=!next||next.tagName==='H3'||(next.tagName==='TABLE'&&!next.querySelector('tbody tr'));if(!empty||title.nextElementSibling?.classList.contains('empty-state'))return;if(next?.tagName==='TABLE')(next as HTMLElement).style.display='none';const note=document.createElement('p');note.className='empty-state';note.textContent='暂无数据';title.after(note)})};attach();new MutationObserver(attach).observe(document.body,{childList:true,subtree:true})})
onBeforeUnmount(()=>window.removeEventListener('datagov:error',showError))
</script>
<template><RouterView /><div v-if="errorMessage" class="global-error-mask" role="alertdialog" aria-modal="true" @click="dismiss"><section class="global-error-dialog"><button class="error-close" aria-label="关闭错误提示">×</button><span>操作未完成</span><p>{{errorMessage}}</p><small>点击任意位置关闭</small></section></div></template>
<style scoped>.global-error-mask{position:fixed;inset:0;z-index:3000;display:grid;place-items:center;padding:24px;background:rgba(2,12,27,.72);backdrop-filter:blur(5px)}.global-error-dialog{position:relative;width:min(480px,100%);padding:24px;border:1px solid #e27878;border-radius:12px;background:#301d2a;color:#ffe4e4;box-shadow:0 24px 70px rgba(0,0,0,.55)}.error-close{position:absolute;right:12px;top:10px;min-width:34px;height:34px;padding:0;font-size:24px}.global-error-dialog span{font-weight:700;color:#ffaaaa}.global-error-dialog p{margin:10px 0;color:#ffe4e4;white-space:pre-wrap}.global-error-dialog small{color:#e8b0b0}</style>
