package com.example.datagov.modules.auth.application;
import com.example.datagov.infrastructure.Db;import com.example.datagov.common.*;
import org.springframework.stereotype.Component;import org.springframework.boot.ApplicationArguments;import org.springframework.boot.ApplicationRunner;import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;import org.springframework.beans.factory.annotation.Value;import org.springframework.transaction.annotation.Transactional;import org.springframework.security.crypto.password.PasswordEncoder;
/** Opt-in, once on an empty installation. Secrets only from process environment. */
@Component @ConditionalOnProperty(name="app.bootstrap.enabled",havingValue="true")
public class InitialAdministrator implements ApplicationRunner {
 private final Db db;private final PasswordEncoder passwords;private final String org,username,password;
 public InitialAdministrator(Db db,PasswordEncoder passwords,@Value("${BOOTSTRAP_ORG_CODE}") String org,@Value("${BOOTSTRAP_USERNAME}") String username,@Value("${BOOTSTRAP_PASSWORD}") String password){this.db=db;this.passwords=passwords;this.org=org;this.username=username;this.password=password;}
 @Transactional public void run(ApplicationArguments args){Checks.require(db.count("SELECT COUNT(*) FROM user_account")==0,409,ErrorCode.STATE_CONFLICT,"初始化管理员仅适用于空账号库，请关闭BOOTSTRAP_ENABLED后启动");Checks.text(org,64);Checks.text(username,64);Checks.require(password.length()>=12&&password.getBytes(java.nio.charset.StandardCharsets.UTF_8).length<=72,400,ErrorCode.INVALID_REQUEST,"初始化密码必须至少12字符且不超过72字节");String oid=db.insert("INSERT INTO org(code,name,status) VALUES(?,'初始治理组织','ENABLED')",org);String uid=db.insert("INSERT INTO user_account(org_id,username,password_hash,display_name,status) VALUES(?,?,?,'初始系统管理员','ENABLED')",oid,username,passwords.encode(password));db.update("INSERT INTO user_role(user_id,role_id) SELECT ?,id FROM role WHERE code='ROLE-SYSADMIN'",uid);db.update("INSERT INTO user_scope(user_id,org_id,include_descendants,scope_type) VALUES(?,?,1,'ORG')",uid,oid);db.update("INSERT INTO security_event(org_id,actor_id,trace_id,event_code,outcome) VALUES(?,?,'BOOTSTRAP','INITIAL_ADMIN','SUCCESS')",oid,uid);}
}
